services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    volumes:
      - ./api:/app
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASS: pass
      DB_NAME: technews
      DB_PORT: 3306

  db:
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: technews
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - 3306:3306

volumes:
  db_data:
