# Choose whatever you want, version >= 1.16
FROM golang:1.23-alpine AS base

FROM base AS dev
WORKDIR /app

RUN go install github.com/air-verse/air@latest

COPY go.mod  ./
RUN go mod download

CMD ["air", "-c", ".air.toml"]
